import type { Metadata } from "next";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

import { SessionProvider, useSession } from "next-auth/react";

import { auth } from "@/auth";
import ModalProvider from "@/providers/modal-provider";
import { Toaster } from "@/components/ui/sonner";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <SessionProvider session={session}>
        <body className={inter.className}>
          <Toaster position="top-center" richColors />
          <ModalProvider />
          {children}
        </body>
      </SessionProvider>
    </html>
  );
}
